# Generated by Django 5.2.8 on 2026-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_last_active_date_customuser_login_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_intro',
            field=models.BooleanField(default=False),
        ),
    ]
