# Generated by Django 5.2.8 on 2026-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_has_completed_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
