# Generated by Django 5.2.8 on 2026-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='report_screenshots/'),
        ),
    ]
