"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import dj_database_url  # ADD THIS IMPORT

load_dotenv(encoding='utf-8')  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ DEBUG: Print which env file is being used
env_file = BASE_DIR / '.env.local'
print(f"Looking for env file at: {env_file}")
print(f"Env file exists: {env_file.exists()}")

load_dotenv(env_file)

# ✅ DEBUG: Print the Redis URL being used
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
print(f"REDIS_URL: {REDIS_URL}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Environment detection
DEBUG = os.getenv('DEBUG', 'False') == 'True'
SECRET_KEY = os.getenv('SECRET_KEY')

AUTH_USER_MODEL = 'users.CustomUser'

# WebSocket CORS - Add this section
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'aralila-backend.onrender.com']

SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
    '.vercel.app',
] + [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.supabase_auth.SupabaseAuthentication',  
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
# }


# Application definition

INSTALLED_APPS = [
    'daphne',  # ADD THIS FIRST - for WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "channels",
    "games",
    "progress",
    "users",
    "rest_framework",
    "rest_framework_simplejwt",
    "reports",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MOVED: Should be first after security
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"

# CHANGED: Use Redis URL from environment variable
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

print(f"Redis URL: {REDIS_URL}")

try:
    import redis
    r = redis.from_url(REDIS_URL)
    r.ping()
    print("Redis connected successfully")
except Exception as e:
    print(f"Redis connection failed: {e}")

# WebSocket Configuration
WEBSOCKET_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://aralila.vercel.app',
    'https://aralila-project.vercel.app',
]

# Channel layer configuration (using Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": os.getenv('CHANNEL_LAYERS_BACKEND', 'channels_redis.core.RedisChannelLayer'),
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1500,
            "expiry": 10,
            # Add connection settings
            "channel_capacity": {
                "http.request": 200,
                "http.response": 200,
                "websocket.send*": 1000,
                "websocket.receive*": 1000,
            },
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL = os.getenv('DATABASE_URL')
# if DATABASE_URL:
#     # Use dj_database_url to parse connection string
#     DATABASES = {
#         'default': {
#             **dj_database_url.parse(DATABASE_URL),
#             'CONN_MAX_AGE': 600,
#             'CONN_HEALTH_CHECKS': True,
#             'OPTIONS': {
#                 'sslmode': 'require',
#                 'connect_timeout': 10,
#             }
#         }
#     }
# else:
#     # Fallback to SQLite for development
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
# not my database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  
        'USER': 'postgres.dnrwenixinuxocwdlmwk',  
        'PASSWORD': 'F4-aralila-db*SR',
        'HOST': 'aws-1-ap-southeast-1.pooler.supabase.com',
        'PORT': '6543',
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 0,
    }
}


# my database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',  
#         'USER': 'postgres.sovnysawenldkipowbia',  
#         'PASSWORD': 'Aralila12325',
#         'HOST': 'aws-1-ap-southeast-2.pooler.supabase.com',
#         'PORT': '6543',
#         'OPTIONS': {
#             'sslmode': 'require',
#             'connect_timeout': 10,
#         },
#         'CONN_MAX_AGE': 0,
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'  # CHANGED: Philippine timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CHANGED: Secure CORS configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    os.getenv('FRONTEND_URL', 'http://localhost:3000'),
    "https://aralila.vercel.app", 
    "https://aralila-project.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ADD: CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
    'https://aralila.vercel.app',
    "https://aralila-project.vercel.app",
    'https://aralila-backend.onrender.com',
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# ADD: Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Trust Render's proxy headers
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ADD: Logging configuration for production debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}